# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:22.12-alpine AS builder

# Set the working directory inside the Docker image
WORKDIR /app

# Copy the package.json and package-lock.json to install dependencies
COPY package.json /app/package.json

# Install dependencies (npm will be cached if package.json hasn't changed)
RUN --mount=type=cache,target=/root/.npm npm install

# Copy the rest of the application source code
COPY . /app

# Build the application
RUN npm run build

# Create a production image
FROM node:22-alpine

# Set the working directory inside the Docker image
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --ignore-scripts --omit-dev

# Declare the environment variables required by the application
ENV JINAAI_API_KEY=your-jinaai-api-key

# Expose the port the app runs on
EXPOSE 3000

# Run the application
ENTRYPOINT ["node", "dist/index.js"]